config/routes.rb
Dragon::Application.routes.draw do

  resources :minutes_samples

  resources :prelaunches

  resources :agenda_samples

  match "/prelaunch_list", to: 'prelaunches#new'
  match "/about", to: 'home#about'
  match "/contact", to: 'home#contact'
  match "/pricing", to: 'home#pricing'
  match "/tour", to: 'home#tour'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users

  resources :users, :only => [:show, :index]  do
    resources :meetings
  end

  match "/articles", to: 'static_pages#articles'
  match "how_to_make_a_meeting_agenda", to: 'static_pages#agenda_how_to'
  match "what_is_a_meeting_agenda", to: 'static_pages#what_is_a_meeting_agenda'
  match "how_to_run_an_effective_meeting", to: 'static_pages#effective_meeting'
  match "why_take_meeting_minutes", to: 'static_pages#why_take_meeting_minutes'
  match "important_aspects_to_consider_for_meeting", to: 'static_pages#important_aspects_for_meeting'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/agenda_sample.rb
class AgendaSample < ActiveRecord::Base
  attr_accessible :email
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :end_time, :location, :logo_url, :reason, :start_time, :title

end

app/models/minutes_sample.rb
class MinutesSample < ActiveRecord::Base
  attr_accessible :email
end

app/models/prelaunch.rb
class Prelaunch < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


end

app/controllers/agenda_samples_controller.rb
class AgendaSamplesController < InheritedResources::Base



  def create
    @agenda_sample = AgendaSample.new(params[:agenda_sample])
    if @agenda_sample.save
      Notifier.agenda_confirmation(@agenda_sample).deliver
      redirect_to root_path, notice: "Please Check you Email for the Agenda Template."
    else
      render :new
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def contact
  end

  def index
    @users = User.all
    if user_signed_in?
      @meetings = Meeting.where(:user_id => [current_user.id])
    else
      ""
    end
  end

  def pricing
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :setup_user




  def index
    @meetings = Meeting.where(:user_id => [current_user.id])
  end


  def show
    @meeting = Meeting.find(params[:id])
  end




  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # prelaunch_list.html.erb
      format.json { render json: @meeting }
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end


  def create
    @meeting = @user.meetings.build(params[:meeting])
    if @meeting.save
      redirect_to user_meetings_path, :notice => "Your meeting has been created!"
    else
      render :new
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update_attributes(params[:meeting])
      redirect_to user_meetings_path, :notice => "Your Meeting has been updated!"
    else
      render :edit
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if @meeting.destroy
      redirect_to user_meetings_path, :notice => "Meeting Destroyed"
    else
      render :index
    end
  end


  def setup_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/prelaunches_controller.rb
class PrelaunchesController < InheritedResources::Base



  def create
    @prelaunch = Prelaunch.new(params[:prelaunch])
    if @prelaunch.save
      Notifier.prelaunch_confirmation(@prelaunch).deliver
      redirect_to root_path, notice: "Thank you for Signing Up, We'll let you know when we launch'"
    else
      render :new
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  @agenda_sample = AgendaSample.new



  def articles
  end

  def what_is_a_meeting_agenda
    @agenda_sample = AgendaSample.new
  end

  def effective_meeting
    @agenda_sample = AgendaSample.new
  end

  def agenda_how_to
    @agenda_sample = AgendaSample.new
  end

  def why_take_meeting_minutes
    @agenda_sample = AgendaSample.new
  end

  def important_aspects_for_meeting
    @agenda_sample = AgendaSample.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!


  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/agenda_samples_helper.rb
module AgendaSamplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description}
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/minutes_samples_helper.rb
module MinutesSamplesHelper
end

app/helpers/prelaunches_helper.rb
module PrelaunchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agenda_samples/_new.html.erb
<div>

    <h2>
      Get A FREE Agenda Template ($83 value):

      <%= simple_form_for(@agenda_sample) do |f| %>
          <%= f.error_notification %>

          <div class="well form-vertical">
            <%= f.input :email, :placeholder =>  'Your Email:', :label =>"Don't worry, we hate spam too!" %>
            <button type="submit" class="btn">SEND IT TO ME</button>
          </div>
      <% end %>

    </h2>

</div>

app/views/agenda_samples/new.html.erb
<% title 'Agenda Templates' %>

<% description 'Agenda Templates, create a great agenda in under five minutes' %>

<div class="hero-unit center">
  <h1>Agenda Templates</h1>
  <h2>
    Writing effective meeting agendas takes practice.
    Check out a couple of agenda templates to get an
    idea how you should structure your content to give
    you the best chance of having an effective meeting.
  </h2>

  <br />

  <h2>
    Get A FREE Agenda Template ($83 value):

<%= simple_form_for(@agenda_sample) do |f| %>
    <%= f.error_notification %>

    <div class="well form-vertical">
      <%= f.input :email, :placeholder =>  'Your Email:', :label =>"Don't worry, we hate spam too!" %>
      <button type="submit" class="btn">SEND IT TO ME</button>
    </div>
<% end %>


<%= link_to 'Back', root_path %>

  </h2>
</div>

app/views/meetings/_form.html.erb
<%= simple_form_for [@user, @meeting] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :logo_url %>
    <%= f.input :reason %>
    <%= f.input :location %>
    <%= f.input :date %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/_partialindex.html.erb
<% content_for :sidebar do %>

<table>
  <tr>
    <th>Title</th>
    <th>Reason</th>
    <th>Date</th>
    <th>Start time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.title %></td>
    <td><%= meeting.reason %></td>
    <td><%= meeting.date %></td>
    <td><%= meeting.start_time %></td>


  </tr>
<% end %>
</table>
<% end %>

app/views/meetings/edit.html.erb
<div class="fluid hero-unit">

<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', user_meeting_path %> |
<%= link_to 'Back', user_meetings_path %>

</div>

app/views/meetings/index.html.erb
<div class="fluid hero-unit">
<h1>Listing Meetings</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Logo url</th>
    <th>Reason</th>
    <th>Location</th>
    <th>Date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>User</th>


  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.title %></td>
    <td><%= meeting.logo_url %></td>
    <td><%= meeting.reason %></td>
    <td><%= meeting.location %></td>
    <td><%= meeting.date %></td>
    <td><%= meeting.start_time %></td>
    <td><%= meeting.end_time %></td>
    <td><%= meeting.user_id %></td>
    <td>
      <%= link_to 'show', user_meeting_path(@user, meeting) %><br />
      <%= link_to 'Edit', edit_user_meeting_path(@user, meeting) %><br />
      <%= link_to 'Destroy', user_meeting_path(@user, meeting) ,
                  confirm: 'Are you sure?',
                  method: :delete %>
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_user_meeting_path %>

</div>

app/views/meetings/new.html.erb
<div class="fluid hero-unit">
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', user_meetings_path %>
</div>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="fluid hero-unit">
<p>
  <b>Title:</b>
  <%= @meeting.title %>
</p>

<p>
  <b>Logo url:</b>
  <%= @meeting.logo_url %>
</p>

<p>
  <b>Reason:</b>
  <%= @meeting.reason %>
</p>

<p>
  <b>Location:</b>
  <%= @meeting.location %>
</p>

<p>
  <b>Date:</b>
  <%= @meeting.date %>
</p>

<p>
  <b>Start time:</b>
  <%= @meeting.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @meeting.end_time %>
</p>

<p>
  <b>User:</b>
  <%= @meeting.user_id %>
</p>



<%= link_to 'Back', user_meetings_path %>  |
<%= link_to 'Edit', edit_user_meeting_path %>


</div>

app/views/prelaunches/new.html.erb
<% title 'Meetingfix Prelaunch List' %>
<% description 'Submit your email and we will notify you when
meetingfix launches' %>


<div class="span8 offset1 fluid hero-unit">
  <h1>We're Launching Soon</h1>

  <h3>We will notify you when we launch, it wont be too long now...  </h3>

  <br />
  <small>Don't worry, We hate spam too.</small>
  <br />



  <%= simple_form_for(@prelaunch) do |f| %>
    <%= f.error_notification %>

  <form class="well form-vertical">
    <%= f.input :name, :placeholder =>  'Your Name:', :label =>"*" %>
    <br />
    <br />

    <%= f.input :email, :placeholder =>  'Your Email:', :label =>"Don't worry, we hate spam too!" %><br /> <br />
    <button type="submit" class="btn">Let me know</button>
  </form>
<% end %>







<%= link_to 'Back', root_path %>

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>