config/routes.rb
Dragon::Application.routes.draw do

  resources :minutes_samples

  resources :prelaunches

  resources :agenda_samples

  match "/prelaunch_list", to: 'prelaunches#new'
  match "/about", to: 'home#about'
  match "/contact", to: 'home#contact'
  match "/pricing", to: 'home#pricing'
  match "/tour", to: 'home#tour'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users

  resources :users, :only => [:show, :index]  do
    resources :meetings
  end

  match "/articles", to: 'static_pages#articles'
  match "how_to_make_a_meeting_agenda", to: 'static_pages#agenda_how_to'
  match "what_is_a_meeting_agenda", to: 'static_pages#what_is_a_meeting_agenda'
  match "how_to_run_an_effective_meeting", to: 'static_pages#effective_meeting'
  match "why_take_meeting_minutes", to: 'static_pages#why_take_meeting_minutes'
  match "important_aspects_to_consider_for_meeting", to: 'static_pages#important_aspects_for_meeting'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/agenda_sample.rb
class AgendaSample < ActiveRecord::Base
  attr_accessible :email
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :end_time, :location, :logo_url, :reason, :start_time, :title

end

app/models/minutes_sample.rb
class MinutesSample < ActiveRecord::Base
  attr_accessible :email
end

app/models/prelaunch.rb
class Prelaunch < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def contact
  end

  def index
    @users = User.all
    if user_signed_in?
      @meetings = Meeting.where(:user_id => [current_user.id])
    else
      ""
    end
  end

  def pricing
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :setup_user




  def index
    @meetings = Meeting.where(:user_id => [current_user.id])
  end


  def show
    @meeting = Meeting.find(params[:id])
  end




  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # prelaunch_list.html.erb
      format.json { render json: @meeting }
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end


  def create
    @meeting = @user.meetings.build(params[:meeting])
    if @meeting.save
      redirect_to user_meetings_path, :notice => "Your meeting has been created!"
    else
      render :new
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update_attributes(params[:meeting])
      redirect_to user_meetings_path, :notice => "Your Meeting has been updated!"
    else
      render :edit
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if @meeting.destroy
      redirect_to user_meetings_path, :notice => "Meeting Destroyed"
    else
      render :index
    end
  end


  def setup_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!


  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/agenda_samples_helper.rb
module AgendaSamplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description}
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/minutes_samples_helper.rb
module MinutesSamplesHelper
end

app/helpers/prelaunches_helper.rb
module PrelaunchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<%- flash.each do |type, message| %>
  <div>
    <div  class="alert alert-success">
      <%= content_tag :div, message, :id => "flash_#{type}", :class => "flash #{type}" do %>
        <p><%= message %></p>
      <%- end %>
    </div>
  </div>
<%- end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright © 2012 Meetingfix.com. All Rights Reserved.
  </small>
  <nav>
    <ul class="nav-bar">
      <li><%= link_to "Agenda Templates", new_agenda_sample_path %></li>
      <li><%= link_to "Meeting Minutes Templates", new_minutes_sample_path %></li>
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a id="logo" href="/">MeetingFix</a>
      <nav>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
            <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
            <li><%= link_to 'Meetings', user_meetings_path(current_user) %></li>
            <li><%= link_to('Edit account', edit_user_registration_path) %></li>
            <% if current_user.has_role? :admin %>
                <li><%= link_to('Admin', users_path) %></li>
            <% end %>
        <% else %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Tour', tour_path %></li>
            <li><%= link_to 'Pricing', pricing_path %></li>
            <li><%= link_to 'About Us', about_path %></li>

        <% end %>
      </ul>
      </nav>
    </div>
  </div>
  <%= render 'layouts/tracking' %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_tracking.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32621075-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetingFix | <%= title = (yield :title); title.blank? ? "" : title %></title>
  <meta name="description" content="<%= description = (yield :description) %>" />

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/flash', :flash => flash %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/notifier/agenda_confirmation.text.erb
<%= @agenda_sample.email %>,

Thank you for requesting a Free Agenda Template.   We've attached it to this email,
thanks.


David

app/views/notifier/minutes_confirmation.text.erb


<%= @minutes_sample.email %>,

Thank you for requesting a Free Meeting Minutes Template.   We've attached it to this email, thanks.


Regards,

David

app/views/notifier/prelaunch_confirmation.text.erb
Thank you <%= @prelaunch.name %>,

We will email you as soon as we launch!

Have a great day


David
MeetingFix.com

app/views/prelaunch_emails/new.html.erb
<div class="span8 offset1 fluid hero-unit">
<h1>We're Launching Soon</h1>

We will notify you when we launch, it wont be too long now...

  <%= button_to "Get on the list!", "http://eepurl.com/mlKDL" , class: "btn btn-large btn-success" %>

</div>